/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "var(--color-tertiary-container)",
        "surface": "var(--color-surface)",
        "on-error": "var(--color-on-error)",
        "error": "var(--color-error)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "background": "var(--color-background)",
        "error-container": "var(--color-error-container)",
        "on-primary": "var(--color-on-primary)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-container-high": "var(--color-surface-container-high)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "outline": "var(--color-outline)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface": "var(--color-on-surface)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-tertiary": "var(--color-on-tertiary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-background": "var(--color-on-background)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "secondary": "var(--color-secondary)",
        "surface-container": "var(--color-surface-container)",
        "primary": "var(--color-primary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "outline-variant": "var(--color-outline-variant)",
        "on-secondary": "var(--color-on-secondary)",
        "tertiary": "var(--color-tertiary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-dim": "var(--color-surface-dim)",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", "2xl": "1rem", full: "9999px" },
      spacing: { "margin-desktop": "32px", "container-padding": "24px", "gutter": "16px", "unit": "8px", "margin-mobile": "16px" },
      fontFamily: { sans: ["Inter", "sans-serif"], mono: ["JetBrains Mono", "monospace"] },
      boxShadow: {
        1: "0px 1px 2px 0px rgba(0,0,0,0.3), 0px 1px 3px 1px rgba(0,0,0,0.15)",
        2: "0px 1px 2px 0px rgba(0,0,0,0.3), 0px 2px 6px 2px rgba(0,0,0,0.15)",
        3: "0px 1px 3px 0px rgba(0,0,0,0.3), 0px 4px 8px 3px rgba(0,0,0,0.15)",
        4: "0px 2px 3px 0px rgba(0,0,0,0.3), 0px 6px 10px 4px rgba(0,0,0,0.15)",
        5: "0px 4px 4px 0px rgba(0,0,0,0.3), 0px 8px 12px 6px rgba(0,0,0,0.15)",
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
